trial/SCHousingCrisis-master/Foo/config/routes.rb
 Rails.application.routes.draw do
  devise_for :accounts, path_names: {sign_in: "login", sign_out: "logout" }
  resources :users

  root 'users#index'

  resources :users do
    member do
      post 'upvote'
      put "like", to: "links#upvote"
      put "dislike", to: "link#downvote" 
    end
  end 



  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

trial/SCHousingCrisis-master/Foo/app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(account)
    account ||= Account.new #guest user
        can :read, :all
    end







    #   acccount ||= Account.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
end

trial/SCHousingCrisis-master/Foo/app/models/account.rb
class Account < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  attr_accessible :email, :password, :password_confirmation, :remember_me



end

trial/SCHousingCrisis-master/Foo/app/models/user.rb
class User < ActiveRecord::Base
	
	def self.search(search)
		if search
			where("street LIKE ? OR city LIKE ? OR zip LIKE ? " , "%#{search}%","%#{search}%", "%#{search}%")
		else
			self.all
		end
	end


	acts_as_votable

	def score
		self.get_upvotes.size - self.get_downvotes.size
	end

	geocoded_by :address
		def address
			[street, city, zip].compact.join(',')
			end
	after_validation :geocode

end

trial/SCHousingCrisis-master/Foo/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_ability 
  	@current_ability ||= Ability.new(current_account)
  end

end

trial/SCHousingCrisis-master/Foo/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_account!, except: [:index, :show]


  # GET /users
  # GET /users.json
  def index
        @users = User.search(params[:search]).paginate(:page => params[:page], :per_page => 3)
        @hash = Gmaps4rails.build_markers(@users) do |user, marker|
          marker.lat user.latitude
          marker.lng user.longitude
          marker.infowindow user.street
        end

      end



      def upvote
        @users = User.find(params[:id])
        @users.upvote_by current_account
        redirect_to user_path 
      end

      def downvote
        @users = User.find(params[:id])
        @users.downvote_by current_account
        redirect_to user_path
      end


  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
    if current_account != @user.account
      #redirect them to and error page - make an error page
    else
      #render the view
    end
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:latitude, :longitude, :name, :street, :city, :zip, :gender, :rentPerMonth, :phone, :email)
    end
end

trial/SCHousingCrisis-master/Foo/app/helpers/application_helper.rb
module ApplicationHelper
end

trial/SCHousingCrisis-master/Foo/app/helpers/users_helper.rb
module UsersHelper
end

trial/SCHousingCrisis-master/Foo/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Foo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

	<div id="container">
		<div id="account_nav">
			<% if account_signed_in? %>
				Logged in as <strong><%= current_account.email %></strong>.
				<%= link_to 'Edit profile', edit_account_registration_path %>
				<%= link_to "Logout", destroy_account_session_path, method: :delete %>
			<% else %>
				<%= link_to 'Home', users_path %>
				<%= link_to "Sign up", new_account_registration_path %>
				<%= link_to "Login", new_account_session_path %>
			<% end %>

			<% flash.each do |name, msg| %>
				<%= content_tag :div, msg, id: "flash_#{name}" %>
			<% end %>

			<%= yield %>
		</div>
	</div>


</body>
</html>

trial/SCHousingCrisis-master/Foo/app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :latitude %><br>
    <%= f.text_field :latitude %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br>
    <%= f.text_field :longitude %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :street %><br>
    <%= f.text_field :street %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :zip %><br>
    <%= f.text_field :zip %>
  </div>
  <div class="field">
    <%= f.label :gender %><br>
    <%= f.text_field :gender %>
  </div>
  <div class="field">
    <%= f.label :rentPerMonth %><br>
    <%= f.text_field :rentPerMonth %>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

trial/SCHousingCrisis-master/Foo/app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

trial/SCHousingCrisis-master/Foo/app/views/users/index.html.erb
<script src="//maps.google.com/maps/api/js?v=3.18&sensor=false&client=&key=&libraries=geometry&language=&hl=&region="></script> 
<script src="//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js"></script>
<script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/infobox/1.1.9/src/infobox_packed.js' type='text/javascript'></script> <!-- only if you need custom infoboxes -->

<p id="notice"><%= notice %></p>


<%= form_tag users_path, :method => 'get' do %>
  <p>
    <%= text_field_tag :search, params[:search] %>
    <%= button_tag "Search",:type => 'search', :name => nil %>
  </p>
   
<% end %>

<h1>Available Housing</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Street</th>
      <th>City</th>
      <th>Zip</th>
      <th>Gender</th>
      <th>Rent Per Month</th>
      <th>Phone</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.street %></td>
        <td><%= user.city %></td>
        <td><%= user.zip %></td>
        <td><%= user.gender %></td>
        <td><%= user.rentPerMonth %></td>
        <td><%= user.phone %></td>
        <td><%= user.email %></td>

        <td><%= link_to 'Show', user %></td>

    
          <td><%= link_to 'Edit', edit_user_path(user) %></td>
     
 
          <td><%= link_to 'Destroy', user, method: :delete, data: {confirm: 'Are you sure?'} %></td>
      
     
      <!-- Upvote and downvote route -->
      <td><%= button_to '+1', like_user_path(user), method: :put %></td>
      <td><%= button_to '-1', dislike_user_path(user), method: :put %></td>
      <td><%= user.score %></td>
      </tr>
    <% end %>
  </tbody>
</table>

    <br>
    <%= will_paginate @user %>
    <br>


<br>
 <h1><a href="#" onclick="alert(JSON.stringify(gon.geolocs, null, 4)); return false">Click Here</a></h1>
<%= link_to 'New User', new_user_path %>

<div style='width: 800px;'>
  <div id="map" style='width: 800px; height: 400px;'></div>
</div>

<script type="text/javascript">
var map;
handler = Gmaps.build('Google');
handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
  markers = handler.addMarkers(<%=raw @hash.to_json %>);
  handler.bounds.extendWith(markers);
  handler.fitMapToBounds();
});
</script>

trial/SCHousingCrisis-master/Foo/app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

trial/SCHousingCrisis-master/Foo/app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Latitude:</strong>
  <%= @user.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @user.longitude %>
</p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @user.address %>
</p>

<p>
  <strong>City:</strong>
  <%= @user.city %>
</p>

<p>
  <strong>Zip:</strong>
  <%= @user.zip %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @user.gender %>
</p>

<p>
  <strong>Rentpermonth:</strong>
  <%= @user.rentPerMonth %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @user.phone %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>