trial/config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}
  resources :listings do
    member do
    put "like", to: "listings#upvote"
    end
  end

  root 'listings#index'

end

trial/app/models/ability.rb
class Ability
  include CanCan::Ability
  def initialize(user)
    if user
    user ||= User.new 
    can :read, :all
    can :create, :all
    can :destroy, :all, :user_id => user.id
    can :update, :all, :user_id => user.id
    can :upvote, :all
    
    
   else
    can :read, :all
    can :create, :all
   end
end
end

trial/app/models/listing.rb
class Listing < ActiveRecord::Base
	acts_as_votable
	belongs_to :user

	def self.search(search)
		if search
			where("street LIKE ? OR city LIKE ? OR zip LIKE ? " , "%#{search}%","%#{search}%", "%#{search}%")
		else
			self.all
		end
	end

	geocoded_by :address
		def address
			[street, city, zip].compact.join(',')
			end
	after_validation :geocode
end

trial/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  attr_accessible :email, :password, :password_confirmation, :remember_me

  has_many :listings
end

trial/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

trial/app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  
  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_url, :alert => exception.message
  end
  before_action :set_listing, only: [:show, :edit, :update, :destroy, :upvote]
  before_filter :authenticate_user!, except: [:index, :show]
  load_and_authorize_resource
   include CanCan::ControllerAdditions

  # GET /listings
  # GET /listings.json
  def index
        @search = Listing.ransack(params[:q])
        @listings = @search.result
        @search.build_condition
        @hash = Gmaps4rails.build_markers(@listings) do |listing, marker|
          marker.lat listing.latitude
          marker.lng listing.longitude
          marker.infowindow listing.street
        end
  end

  # GET /listings/1
  # GET /listings/1.json
  def show
  end

  # GET /listings/new
  def new

    @listing = current_user.listings.build
  end

  # GET /listings/1/edit
  def edit
  end

  # POST /listings
  # POST /listings.json
  def create
    @listing = current_user.listings.build(listing_params)



    respond_to do |format|
      if @listing.save
        format.html { redirect_to @listing, notice: 'Listing was successfully created.' }
        format.json { render :show, status: :created, location: @listing }
      else
        format.html { render :new }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /listings/1
  # PATCH/PUT /listings/1.json
  def update
    respond_to do |format|
      if @listing.update(listing_params)
        format.html { redirect_to @listing, notice: 'Listing was successfully updated.' }
        format.json { render :show, status: :ok, location: @listing }
      else
        format.html { render :edit }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /listings/1
  # DELETE /listings/1.json
  def destroy
    @listing.destroy
    respond_to do |format|
      format.html { redirect_to listings_url, notice: 'Listing was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def upvote
    @listing = Listing.find(params[:id])
    @listing.upvote_by current_user
    redirect_to :back
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_listing
      @listing = Listing.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def listing_params
      params.require(:listing).permit(:name, :phone, :email, :street, :city, :state, :zip, :priceperm, :latitude, :longitude, :description)
    end
end

trial/app/helpers/application_helper.rb
module ApplicationHelper

end

trial/app/helpers/listings_helper.rb
module ListingsHelper
end

trial/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bam</title>
  	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
 	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  	<%= csrf_meta_tags %>
</head>
<body>
	<header>
		<div class="header_inner">
				<%= link_to image_tag('logo.svg'), root_path, :id => 'logo' %>
			  <nav>
			  	  <% if can? :create, Listing %>
				    <%= link_to 'Post a Listing', new_listing_path %>
				  <% end %>
			    <% if user_signed_in? %>
					<%= link_to 'Profile', edit_user_registration_path %>
			    	<%= link_to "Logout", destroy_user_session_path, method: :delete %>
			    <% else %>
					<%= link_to "Login", new_user_session_path %>
					<%= link_to "Register", new_user_registration_path %>
				<% end %>
			</nav>
		</div>	
	</header>
	<% flash.each do |name, msg| %>
	<%= content_tag :div, msg, id: "flash_#{name}" %>
	<% end %>
	<%= yield %>
</body>
</html>

trial/app/views/listings/_form.html.erb
<div id="form">
<fieldset>
<%= form_for @listing, html: { multipart: true } do |f| %>
  <% if @listing.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@listing.errors.count, "error") %> prohibited this listing from being saved:</h2>

      <ul>
      <% @listing.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_field :phone %>
  </div>

  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>

  <div class="field">
    <%= f.label :street %><br>
    <%= f.text_field :street %>
  </div>

  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>

  <div class="field">
    <%= f.label :state %><br>
    <%= f.text_field :state %>
  </div>

  <div class="field">
    <%= f.label :zip %><br>
    <%= f.text_field :zip %>
  </div>

  <div class="field">
    <%= f.label :priceperm %><br>
    <%= f.number_field :priceperm %>
  </div>

  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>

  <div class="actions">
    <%= f.submit :class => 'button button_highlight button_block' %>
  </div>
<% end %>
</fieldset>
</div>

trial/app/views/listings/edit.html.erb
<h1>Editing Listing</h1>

<%= render 'form' %>

<%= link_to 'Show', @listing %> |
<%= link_to 'Back', listings_path %>

trial/app/views/listings/index.html.erb
<script src="//maps.google.com/maps/api/js?v=3.18&sensor=false&client=&key=&libraries=geometry&language=&hl=&region="></script> 
<script src="//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js"></script>
<!-- only if you need custom infoboxes -->

<div id="banner_welcome">
  <div class="banner_content">
    <h1>CruzRent</h1>
    <p>Find a rental in Santa Cruz County</p>
    <button><%= link_to "Register", new_user_registration_path, :class => 'button' %></button>
  </div>
</div>

<div class="testimonial">
  <div class="wrapper">
    <!-- Search Bar method for housing -->
     <p style="text-align:center"><%= search_form_for @search do |f| %>
         <%= f.condition_fields do |c| %>
          <%= c.attribute_fields do |a| %>
            <%= a.attribute_select %>
          <% end %>
          <%= c.predicate_select %>
          <%= c.value_fields do |v| %>
            <%= v.text_field :value, :style => 'width: 400px !important' %>
          <% end %>
          <%= f.submit "Search", :class => 'button button-highlight' %>
          <%end %>
      <% end %>
    </p>
  </div>
</div>
<br>
    

    <!-- Header of the listing columns -->

    <table>
      <thead>
        <tr>
          <th>Name</th>
          <th>Phone</th>
          <th>Email</th>
          <th>Street</th>
          <th>City</th>
          <th>State</th>
          <th>Zip</th>
          <th style="padding-left: 5px">Price Per Month</th>
          <th colspan="3"></th>
        </tr>
      </thead>
      <!-- Body of the listing columns -->
      <tbody>
        <% @listings.each do |listing| %>
          <tr>
            <td><%= listing.name %></td>
            <td><%= listing.phone %></td>
            <td><%= listing.email %></td>
            <td><%= listing.street %></td>
            <td><%= listing.city %></td>
            <td><%= listing.state %></td>
            <td><%= listing.zip %></td>
            <td style="padding-left: 5px"><%= listing.priceperm %></td>
            <td><%= link_to 'Show', listing %></td>
            <td><%= link_to 'Edit', edit_listing_path(listing) %></td>
            <td><%= link_to 'Destroy', listing, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>




  <div style='width: 800px;
    top:0;
    bottom: 0;
    left: 0;
    right: 0;

    margin: auto;'>
    <div id="map" style='width: 800px; height: 400px;'></div>
  </div>

  <script type="text/javascript">
  var map;
  handler = Gmaps.build('Google');
  handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
    markers = handler.addMarkers(<%=raw @hash.to_json %>);
    handler.bounds.extendWith(markers);
    handler.fitMapToBounds();
  });
  </script>

trial/app/views/listings/new.html.erb
<h1>New Listing</h1>

<%= render 'form' %>

<%= link_to 'Back', listings_path %>

trial/app/views/listings/show.html.erb
<div id="form">
<fieldset>
  <div style="padding-left: 2em; padding-right:2em;"><h1>Showing the listing at "<%= @listing.street %>"</h1></div>
<p id="notice"><%= notice %></p>

<div class="form-group">
  <div class="col-md-5", style="padding-left:2em;  padding-right:2em;">
      <p>
        <strong>Name:</strong>
        <%= @listing.name %>
      </p>

      <p>
        <strong>Phone:</strong>
        <%= @listing.phone %>
      </p>

      <p>
        <strong>Email:</strong>
        <%= @listing.email %>
      </p>

      <p>
        <strong>Street:</strong>
        <%= @listing.street %>
      </p>

      <p>
        <strong>City:</strong>
        <%= @listing.city %>
      </p>

      <p>
        <strong>State:</strong>
        <%= @listing.state %>
      </p>

      <p>
        <strong>Zip:</strong>
        <%= @listing.zip %>
      </p>

      <p>
        <strong>Priceperm:</strong>
        <%= @listing.priceperm %>
      </p>

      <p>
        <strong>Description:</strong>
        <%= @listing.description %>
      </p>
    </div>
  </div>

  <div class="col-md-5", style="padding-left: 2em;">
<%= link_to like_listing_path(@listing), method: :put, class: "button-sm button_highlight" do %>
  <%= @listing.get_upvotes.size %>
<% end %>
<%= link_to 'Edit', edit_listing_path(@listing) %> |
<%= link_to 'Back', listings_path %>
</fieldset>
</div>